#version: '3.8'

services:
  webhook_fa:
    build: 
      context: ./webhook_fa
      dockerfile: Dockerfile
    container_name: webhook_fa_container
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./webhook_fa:/app
    depends_on:
      - mongodb

  website:
    build: 
      context: ./website
      dockerfile: Dockerfile
    container_name: website_container
    restart: unless-stopped
    ports:
      - "1313:1313"
    environment:
      FLASK_APP: app.py
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./website:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db:z
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: whatsapp_data
    command: ["mongod", "--auth"]

volumes:
  mongo_data:
    driver: local
